from datetime import datetime

from database import db_session, init_db
from models import Keyword, Status

init_db()

# populate Status table
status_confirmed = Status(id=1, status="confirmed")
db_session.add(status_confirmed)
db_session.commit()
status_pending = Status(id=2, status="pending")
db_session.add(status_pending)
db_session.commit()
status_deleted = Status(id=3, status="deleted")
db_session.add(status_deleted)
db_session.commit()
status_expired = Status(id=4, status="expired")
db_session.add(status_expired)
db_session.commit()

# pupulate Keywords table
keywords = [
    "LEAVE YOUR NAME",
    "LEAVE A NAME",
    "LEAVE ME",
    "LEAVE US",
    "NUMBER",
    "RETURN YOUR CALL",
    "AS SOON AS POSSIBLE",
    "GET BACK TO YOU",
    "AT THE TONE",
    "A MESSAGE",
    "YOUR MESSAGE",
    "CALL YOU",
    "RIGHT NOW",
    "UNFORTUNATELY",
    "REACHED",
    "A GREAT DAY",
    "A WONDERFUL DAY",
    "VE REACHED",
    "OFFICE HOURS",
    "FROM MONDAY",
    "MONDAY TO",
    "MONDAY THROUGH",
    "BUSINESS HOURS",
    "TAKE YOUR CALL",
    "CALL BACK",
    "ANSWER YOUR",
    "UNABLE",
    "IF YOU KNOW",
    "TO CONTINUE",
    "VE DIALED",
    "PRESS ONE",
    "PRESS TWO",
    "PRESS THREE",
    "PRESS FOUR",
    "PRESS FIVE",
    "PRESS SIX",
    "PRESS SEVEN",
    "PRESS EIGHT",
    "PRESS NINE",
    "PRESS ZERO",
    "PRESS POUND",
    "PRESS STAR",
    "RECORDED",
    "AFTER THE BEEP",
    "UNAVAILABLE",
    "IS CLOSED",
    "ARE CLOSED",
    "NOW CLOSED",
    "AN EMAIL",
    "ANSWERING MACHINE",
    "NOT IN SERVICE",
    "IS LOCATED",
    "ELEVEN AM TO",
    "TEN AM TO",
    "NINE AM TO",
    "EIGHT AM TO",
    "SEVEN AM TO",
    "SEVEN THIRTY AM TO",
    "TO FIVE PM",
    "TO SIX PM",
    "TO SEVEN PM",
    "TO EIGHT PM",
    "TO NINE PM",
    "VOICEMAIL",
    "AUTOMATED",
    "PROMPT",
    "MAILBOX",
    "RECORD",
    "ANSWERING SERVICE",
    "WELCOME MESSAGE",
    "GENERAL MAILBOX",
    "DIRECTORY PRESS",
    "CURRENTLY AWAY",
    "HOLD PRESS",
    "CLOSED HOLIDAYS",
    "AUTOMATED SYSTEM",
    "SAVE VOICEMAIL",
    "USED VOICEMAIL",
    "CHECK VOICEMAIL",
    "CONFIDENTIAL VOICEMAIL",
    "COMPLETELY AUTOMATED",
    "RECORD TONE",
    "PRESS NUMBER",
    "MESSAGING SYSTEM",
    "REACHED MAILBOX",
    "LEAVE MESSAGE",
    "LEAVE RECORDED",
    "AUTOMATED ATTENDANT",
    "STOP TONE",
    "REACHED AUTOMATED",
    "LEAVE VOICEMAIL",
    "CALLING AUTOMATION",
    "PLEASE HANG",
    "FULLY AUTOMATED",
    "REACH VOICEMAIL",
    "VOICEMAIL LINE",
    "VOICEMAIL SYSTEM",
    "COMMUNICATIONS RECORDED",
    "CALLING VOICEMAIL",
    "AUTOMATED ANSWERING",
    "MAILBOX CAN'T",
    "VIA VOICEMAIL",
    "AUTOMATIC ATTENDANT",
    "PHONE MESSAGE",
    "RECORDED LINE",
    "DIAL EIGHT",
    "MAIN VOICEMAIL",
    "PHONE TREE",
    "PHONE SYSTEM",
    "AUTOMATED VOICEMAIL",
    "AUTOMATIC VOICE",
    "VOICEMAIL BOX",
    "AUTOMATED PHONE",
    "SILENCE MACHINE",
    "RECORDED MESSAGE",
    "REPLAY MESSAGE",
    "AUTOMATED VOICE",
    "VOICE MAILBOX",
    "REMOTE VOICEMAIL",
    "DIAL ONE",
    "AUTOMATED MESSAGE",
    "ALREADY RECORDED",
    "GENERAL VOICEMAIL",
    "ROBOT CALLER",
    "ANSWERING SYSTEM",
    "USING VOICEMAIL",
    "RECORD RECORDING",
    "TELE VOICEMAIL",
    "TEMPORARILY UNAVAILABLE",
    "MAILBOX FULL",
    "ROBO CALLS",
    "AUTOMATED PAYMENTS",
    "PRE RECORDED",
    "QUICK VOICEMAIL",
    "TELL VOICEMAIL",
    "RECORDED CALLS",
    "VOICEMAIL MESSAGES",
    "CALL MACHINE",
    "BEEP PLEASE",
    "REACHED VOICEMAIL"
]
for word in keywords:
    k = Keyword(word=word, date=datetime.now().date(), status_id=1)
    db_session.add(k)
db_session.commit()
